[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sepsis_osc"
version = "0.0.1"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["sepsis_osc"]
