# From gin config at YAIB/configs/tasks/common/PredictionTaskVariables.gin

file_names = {"DYNAMIC": "dyn.parquet", "OUTCOME": "outc.parquet", "STATIC": "sta.parquet"}

vars = {
    "GROUP": "stay_id",
    "SEQUENCE": "time",
    "LABEL": ["sep3_alt", "sofa", "susp_inf_alt"],
    "DYNAMIC": [
        "alb",
        "alp",
        "alt",
        "ast",
        "be",
        "bicar",
        "bili",
        "bili_dir",
        "bnd",
        "bun",
        "ca",
        "cai",
        "ck",
        "ckmb",
        "cl",
        "crea",
        "crp",
        "dbp",
        "fgn",
        "fio2",
        "glu",
        "hgb",
        "hr",
        "inr_pt",
        "k",
        "lact",
        "lymph",
        "map",
        "mch",
        "mchc",
        "mcv",
        "methb",
        "mg",
        "na",
        "neut",
        "o2sat",
        "pco2",
        "ph",
        "phos",
        "plt",
        "po2",
        "ptt",
        "resp",
        "sbp",
        "temp",
        "tnt",
        "urine",
        "wbc",
    ],
    "STATIC": ["age", "sex", "height", "weight"],
}

modality_mapping = {
    "DYNAMIC": [
        "alb",
        "alp",
        "alt",
        "ast",
        "be",
        "bicar",
        "bili",
        "bili_dir",
        "bnd",
        "bun",
        "ca",
        "cai",
        "ck",
        "ckmb",
        "cl",
        "crea",
        "crp",
        "dbp",
        "fgn",
        "fio2",
        "glu",
        "hgb",
        "hr",
        "inr_pt",
        "k",
        "lact",
        "lymph",
        "map",
        "mch",
        "mchc",
        "mcv",
        "methb",
        "mg",
        "na",
        "neut",
        "o2sat",
        "pco2",
        "ph",
        "phos",
        "plt",
        "po2",
        "ptt",
        "resp",
        "sbp",
        "temp",
        "tnt",
        "urine",
        "wbc",
    ],
    "STATIC": ["age", "sex", "height", "weight"],
}
